#include <avr/io.h>
#include <avr/interrupt.h>

void adc_adc_init(){
    // ENABLE ADC
    ADC0.CTRLA = ADC_ENABLE_bm;
    // 2 CLOCK PRESCALER
    ADC0.CTRLB = ADC_PRESC_DIV2_gc;
    // NEED 4 CLK_PER CYCLES @ 3.33MHZ FOR 1US SELECT VDD AS REF
    ADC0.CTRLC = (4 << ADC_TIMEBASE_gp) | ADC_REFSEL_VDD_gc;
    // SAMPLE DURATION OF 64
    ADC0.CTRLE = 64;
    // FREE RUNNING LEFT ADJUST RESULT
    ADC0.CTRLF = ADC_FREERUN_bm | ADC_LEFTADJ_bm;

    ADC0.MUXPOS = ADC_MUXPOS_AIN2_gc;
    // SELECT AIN2 (POTENTIOMENTER R1)
    ADC0.COMMAND = ADC_MODE_SINGLE_8BIT_gc | ADC_START_IMMEDIATE_gc;
}